teleop_twist_joy_node:
  ros__parameters:
    axis_linear: 1
    scale_linear: 0.6
    scale_linear_turbo: 1.0
    axis_angular: 3
    scale_angular: 1.8
    enable_button: 5
    enable_turbo_button: 4
    require_enable_button: true
    use_stamped: false
