velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.6, 0.0, 1.8]
    min_velocity: [-0.6, 0.0, -1.8]
    max_accel: [1.0, 0.0, 2.0]
    max_decel: [-0.5, 0.0, -1.0]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 0.6
